import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'id' | 'en';

// Dictionary
const dictionary = {
  id: {
    dashboard: "Dasbor",
    consoles: "Unit",
    members: "Member",
    reports: "Laporan",
    settings: "Pengaturan",
    logout: "Keluar",
    welcome: "Selamat Datang Kembali",
    overview: "Dasbor",
    overview_subtitle: "Berikut ringkasan performa hari ini.",
    manage_units_desc: "Kelola unit console dan status rental.",
    manage_members_desc: "Kelola data pelanggan dan riwayat main.",
    active_consoles: "Unit Aktif",
    realtime_status: "Status Langsung",
    revenue: "Pendapatan",
    gross_revenue: "Pendapatan Kotor",
    duration: "Durasi Rental",
    total_duration_sub: "Total Durasi Harian",
    total_members: "Total Member",
    registered_sub: "Member Terdaftar",
    recent_tx: "Transaksi Terkini",
    no_tx: "Belum ada transaksi hari ini.",
    console_util: "Utilitas Console",
    add_unit: "Tambah",
    edit_unit: "Edit Unit",
    delete_unit: "Hapus Unit",
    console_name: "Nama Console",
    save: "Simpan",
    cancel: "Batal",
    delete_confirm: "Hapus item ini?",
    status: "Status",
    session_active: "Sesi Aktif",
    stop_session: "Stop Sesi",
    maintenance: "Perbaikan",
    under_maintenance: "Sedang Perbaikan",
    rent_unit: "Sewa Unit",
    select_member: "Pilih Member",
    duration_hrs: "Durasi (Jam)",
    cost: "Biaya",
    total: "Total",
    pay_method: "Metode Pembayaran",
    confirm_pay: "Konfirmasi",
    scan_qris: "Scan QRIS",
    paid_confirm: "Saya Sudah Bayar",
    ready_start: "Siap Dimulai?",
    start_session: "Mulai Sesi",
    search_placeholder: "Cari...",
    sort_name_asc: "Nama (A-Z)",
    sort_name_desc: "Nama (Z-A)",
    sort_playtime: "Terbanyak Main",
    sort_join: "Terlama Daftar",
    filter_all: "Semua Status",
    filter_avail: "Tersedia",
    filter_in_use: "Dipakai",
    add_member: "Tambah",
    edit_member: "Edit Member",
    full_name: "Nama Lengkap",
    phone: "No. HP",
    address: "Alamat",
    join_date: "Tanggal Bergabung",
    notes: "Catatan",
    total_play: "Total Main",
    bonus_balance: "Saldo Bonus",
    bonus_progress: "Progress Bonus",
    bonus_used: "Total Bonus Dipakai",
    history_tx: "Riwayat Transaksi",
    daily_recap: "Rekap Harian",
    all: "Semua",
    system_settings: "Pengaturan Sistem",
    config_subtitle: "Konfigurasi harga, perangkat keras, dan loyalty.",
    rate_and_bonus: "Tarif & Membership",
    hourly_rate: "Harga Rental Per Jam",
    rate_desc: "Harga dasar untuk perhitungan biaya rental.",
    bonus_target: "Target Bonus",
    bonus_desc: "Main X jam",
    reward: "Dapat Bonus",
    reward_desc: "Dapat Y jam",
    save_changes: "Simpan Perubahan",
    saved: "Berhasil Disimpan!",
    login_title: "Masuk Sistem",
    username: "Username",
    password: "Password",
    sign_in: "Masuk",
    access_denied: "Akses Ditolak: Khusus Admin.",
    unit_in_use: "Unit sedang digunakan. Selesaikan sesi terlebih dahulu.",
    no_data_consoles: "Belum ada unit console.",
    no_data_members: "Belum ada data member.",
    system_access: "Akses Sistem",
    membership: "Membership",
    membership_plan: "Jenis Membership",
    price_plan: "Harga Membership",
    active_status: "Status Aktif",
    general_settings: "Umum",
    membership_settings: "Konfigurasi Membership",
    bluetooth_settings: "Koneksi TV & Perangkat",
    bt_connected: "Terhubung ke TV Receiver",
    bt_disconnected: "Tidak Terhubung",
    connect_bt: "Hubungkan Bluetooth",
    disconnect_bt: "Putuskan Koneksi",
    bt_desc: "Hubungkan ke perangkat keras untuk mengontrol daya TV otomatis.",
    developer_info: "Tentang Pengembang",
    developed_by: "Dikembangkan oleh",
    contact_dev: "Hubungi Developer",
    
    // NEW KEYS TRANSLATED
    online: "ONLINE",
    offline: "OFFLINE",
    tv_connected: "TV TERHUBUNG",
    tv_disconnected: "TV TERPUTUS",
    syncing: "SINKRONISASI...",
    synced: "TERSINKRON",
    new_rental_session: "Sesi Rental Baru",
    select_member_placeholder: "-- Pilih Member --",
    duration_label: "Durasi:",
    jam: "Jam",
    total_pay: "Total Bayar:",
    use_bonus: "Pakai Bonus:",
    pay_cash: "TUNAI (CASH)",
    total_bill: "Total Tagihan",
    back: "Kembali",
    scan_to_pay: "Scan untuk Bayar",
    unit_label: "Unit:",
    method_label: "Metode:",
    console_name_placeholder: "misal: PlayStation 5 - Unit 01",
    exp_label: "Exp:",
    upgrade_membership: "Upgrade Membership",
    current_plan: "Saat Ini:",
    select_new_plan: "Pilih Paket Baru",
    confirm_update: "Konfirmasi & Perbarui",
    days_lifetime: "Hari (0 = Seumur Hidup)",
    rule_desc: "Aturan: Main {x} Jam dapat bonus {y} Jam.",
    device_status: "Status Perangkat",
    tv_select_unit: "Pilih unit console yang mewakili layar TV ini:",
    tv_no_consoles: "Tidak ada console ditemukan. Silakan atur di Aplikasi Mobile.",
    tv_reset_id: "Reset ID TV",
    time_remaining: "Sisa Waktu",
    session_ended: "SESI BERAKHIR",
    available_status: "TERSEDIA",
    ready_to_play: "Siap Bermain",
    member_label: "Member:",
    unknown_unit: "Tidak Diketahui",
    hour_short: "Jam",

    // Login Placeholders
    enter_username: "Masukkan username...",
    enter_password: "Masukkan password...",
    invalid_login: "Username atau password salah.",
    
    // Settings & Backup
    tv_connectivity: "Konektivitas TV",
    cloud_link_desc: "Otomatis Aktif. Kontrol TV via Internet/Wi-Fi.",
    bluetooth_connected: "Bluetooth Terhubung",
    bluetooth_disconnected: "Bluetooth Putus",
    data_management: "Manajemen Data",
    smart_cloud_opt: "Smart Cloud Optimizer",
    keep_data_duration: "Simpan Data Cloud Selama:",
    days_30_save: "30 Hari (Hemat)",
    days_90: "90 Hari (3 Bulan)",
    days_365: "1 Tahun",
    forever: "Selamanya",
    backup_restore_desc: "Gunakan fitur ini untuk memindahkan data antar perangkat.\n1. Backup data di perangkat lama.\n2. Kirim file .json ke perangkat baru.\n3. Restore di perangkat baru.",
    backup_btn: "Backup",
    download_data: "Download Data",
    restore_btn: "Restore",
    upload_data: "Upload Data",
    restore_confirm: "Ditemukan backup dari tanggal {date}.\n\nRestore akan MENIMPA semua data yang ada saat ini di perangkat ini.\nApakah Anda yakin ingin melanjutkan?",
    restore_success: "Sukses! Data aplikasi berhasil dipulihkan.",
    restore_error: "Gagal Restore: {msg}",
    invalid_file: "Format file tidak valid atau rusak.",

    // Members & Forms
    upload_or_url: "Upload Foto atau Gunakan URL",
    paste_link_hint: "Paste link gambar langsung (jpg/png)",
    notes_placeholder: "Catatan tambahan...",
    address_placeholder: "Alamat lengkap...",
    dob: "Tanggal Lahir",
    birthday_bonus: "Bonus Ulang Tahun",
    birthday_bonus_desc: "Jam main gratis yang diberikan otomatis saat member berulang tahun.",

    // Consoles
    elapsed: "Jalan",
    remaining: "Sisa",
    add_1_hour: "+1 Jam",
    next_payment: "Lanjut Pembayaran",
    
    // Reports
    export_csv: "Export CSV",
    search_reports_placeholder: "Cari member / unit...",
    total_data_count: "Total: {count} Data",

    // --- NEWLY ADDED FOR AUDIT ---
    since: "Terdaftar",
    joined: "Bergabung",
    verified_member: "Member Terverifikasi",
    member_card_footer: "Kartu Member",
    business_profile: "Profil Bisnis",
    logo_label: "Logo Struk & Aplikasi",
    or_use_url: "Atau gunakan URL gambar:",
    business_name: "Nama Bisnis",
    full_address: "Alamat Lengkap",
    phone_number: "Nomor Telepon",
    print_wifi: "Browser Print / Wi-Fi",
    print_bt: "Bluetooth Thermal",
    select_print_method: "Pilih Metode Cetak",
    receipt_for_tx: "Struk untuk transaksi {name}",
    preview_image: "Preview Gambar",
    sort_usage_desc: "Terbanyak Dipakai",
    sort_date_new: "Tanggal (Baru)",
    sort_date_old: "Tanggal (Lama)",
    sort_cost_hi: "Nominal (Tertinggi)",
    sort_cost_lo: "Nominal (Terendah)",
  },
  en: {
    dashboard: "Dashboard",
    consoles: "Units",
    members: "Members",
    reports: "Reports",
    settings: "Settings",
    logout: "Sign Out",
    welcome: "Welcome Back",
    overview: "Dashboard",
    overview_subtitle: "Here is today's performance summary.",
    manage_units_desc: "Manage consoles and rental status.",
    manage_members_desc: "Manage customers and play history.",
    active_consoles: "Active Units",
    realtime_status: "Real-time Status",
    revenue: "Revenue",
    gross_revenue: "Gross Revenue",
    duration: "Duration",
    total_duration_sub: "Total Daily Duration",
    total_members: "Total Members",
    registered_sub: "Registered",
    recent_tx: "Recent Transactions",
    no_tx: "No transactions today.",
    console_util: "Console Utility",
    add_unit: "Add",
    edit_unit: "Edit Unit",
    delete_unit: "Delete Unit",
    console_name: "Console Name",
    save: "Save",
    cancel: "Cancel",
    delete_confirm: "Delete this item?",
    status: "Status",
    session_active: "Session Active",
    stop_session: "Stop Session",
    maintenance: "Maintenance",
    under_maintenance: "Under Maintenance",
    rent_unit: "Rent Unit",
    select_member: "Select Member",
    duration_hrs: "Duration (Hrs)",
    cost: "Cost",
    total: "Total",
    pay_method: "Payment Method",
    confirm_pay: "Confirm",
    scan_qris: "Scan QRIS",
    paid_confirm: "I Have Paid",
    ready_start: "Ready to Start?",
    start_session: "Start Session",
    search_placeholder: "Search...",
    sort_name_asc: "Name (A-Z)",
    sort_name_desc: "Name (Z-A)",
    sort_playtime: "Most Playtime",
    sort_join: "Oldest Joined",
    filter_all: "All Status",
    filter_avail: "Available",
    filter_in_use: "In Use",
    add_member: "Add",
    edit_member: "Edit Member",
    full_name: "Full Name",
    phone: "Phone No.",
    address: "Address",
    join_date: "Join Date",
    notes: "Notes",
    total_play: "Total Playtime",
    bonus_balance: "Bonus Balance",
    bonus_progress: "Bonus Progress",
    bonus_used: "Total Bonus Used",
    history_tx: "Transaction History",
    daily_recap: "Daily Recap",
    all: "All",
    system_settings: "System Settings",
    config_subtitle: "Configure pricing and loyalty rules.",
    rate_and_bonus: "Rates & Membership",
    hourly_rate: "Hourly Rate",
    rate_desc: "Base price for rental calculation.",
    bonus_target: "Bonus Target",
    bonus_desc: "Play X hours",
    reward: "Reward",
    reward_desc: "Get Y hours",
    save_changes: "Save Changes",
    saved: "Saved Successfully!",
    login_title: "System Login",
    username: "Username",
    password: "Password",
    sign_in: "Sign In",
    access_denied: "Access Denied: Admin only.",
    unit_in_use: "Unit is currently in use. Please stop session first.",
    no_data_consoles: "No console units found.",
    no_data_members: "No members found.",
    system_access: "System Access",
    membership: "Membership",
    membership_plan: "Membership Plan",
    price_plan: "Membership Price",
    active_status: "Active Status",
    general_settings: "General",
    membership_settings: "Membership Config",
    bluetooth_settings: "TV & Device Connection",
    bt_connected: "Connected to TV Receiver",
    bt_disconnected: "Not Connected",
    connect_bt: "Connect Bluetooth",
    disconnect_bt: "Disconnect",
    bt_desc: "Connect to hardware to control TV power automatically.",
    developer_info: "Developer Info",
    developed_by: "Developed by",
    contact_dev: "Contact Developer",
    
    // NEW KEYS TRANSLATED
    online: "ONLINE",
    offline: "OFFLINE",
    tv_connected: "TV CONNECTED",
    tv_disconnected: "TV DISCONNECTED",
    syncing: "SYNCING...",
    synced: "SYNCED",
    new_rental_session: "New Rental Session",
    select_member_placeholder: "-- Select Member --",
    duration_label: "Duration:",
    jam: "Hours",
    total_pay: "Total Pay:",
    use_bonus: "Use Bonus:",
    pay_cash: "CASH",
    total_bill: "Total Bill",
    back: "Back",
    scan_to_pay: "Scan to Pay",
    unit_label: "Unit:",
    method_label: "Method:",
    console_name_placeholder: "e.g. PlayStation 5 - Unit 01",
    exp_label: "Exp:",
    upgrade_membership: "Upgrade Membership",
    current_plan: "Current:",
    select_new_plan: "Select New Plan",
    confirm_update: "Confirm & Update",
    days_lifetime: "Days (0 = Lifetime)",
    rule_desc: "Rule: Play {x} Hours get {y} Hours bonus.",
    device_status: "Device Status",
    tv_select_unit: "Select which console unit represents this TV screen:",
    tv_no_consoles: "No consoles found. Please setup in Mobile App first.",
    tv_reset_id: "Reset TV ID",
    time_remaining: "Time Remaining",
    session_ended: "SESSION ENDED",
    available_status: "AVAILABLE",
    ready_to_play: "Ready to play",
    member_label: "Member:",
    unknown_unit: "Unknown",
    hour_short: "H",

    // Login Placeholders
    enter_username: "Enter username...",
    enter_password: "Enter password...",
    invalid_login: "Invalid username or password.",

    // Settings & Backup
    tv_connectivity: "TV Connectivity",
    cloud_link_desc: "Automatically Active. Control TV via Internet/Wi-Fi.",
    bluetooth_connected: "Bluetooth Connected",
    bluetooth_disconnected: "Bluetooth Disconnected",
    data_management: "Data Management",
    smart_cloud_opt: "Smart Cloud Optimizer",
    keep_data_duration: "Keep Cloud Data For:",
    days_30_save: "30 Days (Save Space)",
    days_90: "90 Days (3 Months)",
    days_365: "1 Year",
    forever: "Forever",
    backup_restore_desc: "Use this to move data between devices.\n1. Backup on old device.\n2. Send .json file to new device.\n3. Restore on new device.",
    backup_btn: "Backup",
    download_data: "Download Data",
    restore_btn: "Restore",
    upload_data: "Upload Data",
    restore_confirm: "Found backup from {date}.\n\nRestore will OVERWRITE all current data on this device.\nAre you sure you want to proceed?",
    restore_success: "Success! Application data restored.",
    restore_error: "Restore Failed: {msg}",
    invalid_file: "File format invalid or corrupted.",

    // Members & Forms
    upload_or_url: "Upload Photo or Use URL",
    paste_link_hint: "Paste image link directly (jpg/png)",
    notes_placeholder: "Additional notes...",
    address_placeholder: "Full address...",
    dob: "Date of Birth",
    birthday_bonus: "Birthday Bonus",
    birthday_bonus_desc: "Free hours automatically given on member's birthday.",

    // Consoles
    elapsed: "Elapsed",
    remaining: "Left",
    add_1_hour: "+1 Hour",
    next_payment: "Proceed to Payment",

    // Reports
    export_csv: "Export CSV",
    search_reports_placeholder: "Search member / unit...",
    total_data_count: "Total: {count} Records",

    // --- NEWLY ADDED FOR AUDIT ---
    since: "Member Since",
    joined: "Joined",
    verified_member: "Verified Member",
    member_card_footer: "Member Card",
    business_profile: "Business Profile",
    logo_label: "Receipt & App Logo",
    or_use_url: "Or use image URL:",
    business_name: "Business Name",
    full_address: "Full Address",
    phone_number: "Phone Number",
    print_wifi: "Browser Print / Wi-Fi",
    print_bt: "Bluetooth Thermal",
    select_print_method: "Select Print Method",
    receipt_for_tx: "Receipt for transaction {name}",
    preview_image: "Image Preview",
    sort_usage_desc: "Most Used",
    sort_date_new: "Date (Newest)",
    sort_date_old: "Date (Oldest)",
    sort_cost_hi: "Cost (Highest)",
    sort_cost_lo: "Cost (Lowest)",
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof dictionary['id'], params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('id');

  useEffect(() => {
    const saved = localStorage.getItem('ziezan_lang') as Language;
    if (saved) setLanguage(saved);
  }, []);

  const changeLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('ziezan_lang', lang);
  };

  const t = (key: keyof typeof dictionary['id'], params?: Record<string, string | number>) => {
    let text = dictionary[language][key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, String(v));
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};